version: "3"
services:
  redis-service:
    image: "redis:alpine"

    command: redis-server

    ports:
     - "6379:6379"

    volumes:
     - $PWD/redis-data:/usr/local/etc/redis
  golang-api:
    build: 
      context: .
    ports: 
      - 3000:3000
    restart: always
    depends_on: 
      - redis-service