apiVersion: apps/v1
kind: Deployment
metadata:
  name: golang-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: golang-api
  template:
    metadata:
      labels:
        app: golang-api
    spec:
      containers:
        - name: golang-api
          image: gcr.io/ipo-mutant-api/golang-api:latest
          imagePullPolicy: Always
          resources:
            requests:
              cpu: 100m
              memory: 100Mi
          ports:
            - containerPort: 80
          env:
            - name: REDIS_PASS
              valueFrom:
                secretKeyRef:
                  name: redis
                  key: REDIS_PASS

---
apiVersion: v1
kind: Service
metadata:
  name: golang-api
spec:
  ports:
    - name: http
      port: 80
      targetPort: 80
      protocol: TCP
  type: LoadBalancer
  loadBalancerIP: "35.222.16.153"

  selector:
    app: golang-api
